export const teams = [
  // Americas
  { id: 1, name: "100 Thieves", power: 78, potential: 83, region: "Americas" },
  { id: 2, name: "Cloud9", power: 77, potential: 81, region: "Americas" },
  { id: 3, name: "Evil Geniuses", power: 72, potential: 78, region: "Americas" },
  { id: 4, name: "FURIA", power: 68, potential: 74, region: "Americas" },
  { id: 5, name: "KRÜ Esports", power: 67, potential: 72, region: "Americas" },
  { id: 6, name: "Leviatan", power: 81, potential: 86, region: "Americas" },
  { id: 7, name: "LOUD", power: 84, potential: 89, region: "Americas" },
  { id: 8, name: "MIBR", power: 64, potential: 69, region: "Americas" },
  { id: 9, name: "NRG", power: 82, potential: 87, region: "Americas" },
  { id: 10, name: "Sentinels", power: 83, potential: 88, region: "Americas" },
  { id: 11, name: "G2 Esports", power: 75, potential: 80, region: "Americas" },
  { id: 12, name: "2GAME Esports", power: 60, potential: 65, region: "Americas" },
  
  // EMEA
  { id: 13, name: "Team Liquid", power: 81, potential: 86, region: "EMEA" },
  { id: 14, name: "GiantX", power: 65, potential: 70, region: "EMEA" },
  { id: 15, name: "Natus Vincere", power: 80, potential: 85, region: "EMEA" },
  { id: 16, name: "Fnatic", power: 88, potential: 92, region: "EMEA" },
  { id: 17, name: "BBL Esports", power: 68, potential: 73, region: "EMEA" },
  { id: 18, name: "Karmine Corp", power: 74, potential: 80, region: "EMEA" },
  { id: 19, name: "Team Heretics", power: 78, potential: 84, region: "EMEA" },
  { id: 20, name: "Vitality", power: 83, potential: 87, region: "EMEA" },
  { id: 21, name: "Apeks", power: 66, potential: 72, region: "EMEA" },
  { id: 22, name: "KOI", power: 63, potential: 68, region: "EMEA" },
  { id: 23, name: "FUT Esports", power: 76, potential: 81, region: "EMEA" },
  { id: 24, name: "Gentle Mates", power: 64, potential: 69, region: "EMEA" },
  
  // Pacific
  { id: 25, name: "Zeta Divison", power: 78, potential: 83, region: "Pacific" },
  { id: 26, name: "Team Secret", power: 69, potential: 74, region: "Pacific" },
  { id: 27, name: "Paper Rex", power: 86, potential: 91, region: "Pacific" },
  { id: 28, name: "DetonationFocusMe", power: 58, potential: 63, region: "Pacific" },
  { id: 29, name: "Gen.G", power: 85, potential: 90, region: "Pacific" },
  { id: 30, name: "DRX", power: 84, potential: 89, region: "Pacific" },
  { id: 31, name: "T1", power: 75, potential: 81, region: "Pacific" },
  { id: 32, name: "Boom Esports", power: 65, potential: 70, region: "Pacific" },
  { id: 33, name: "Nongshim Redforce", power: 62, potential: 68, region: "Pacific" },
  { id: 34, name: "Talon", power: 68, potential: 74, region: "Pacific" },
  { id: 35, name: "Global Esports", power: 60, potential: 66, region: "Pacific" },
  { id: 36, name: "Rex Regum Qeon", power: 67, potential: 73, region: "Pacific" },
  
  // China
  { id: 37, name: "All Gamers", power: 68, potential: 74, region: "China" },
  { id: 38, name: "Edward Gaming", power: 87, potential: 93, region: "China" },
  { id: 39, name: "FunPlus Phoenix", power: 79, potential: 85, region: "China" },
  { id: 40, name: "Wolves Esports", power: 65, potential: 71, region: "China" },
  { id: 41, name: "Bilibili Gaming", power: 74, potential: 80, region: "China" },
  { id: 42, name: "JD Gaming", power: 63, potential: 69, region: "China" },
  { id: 43, name: "Nova Esports", power: 62, potential: 68, region: "China" },
  { id: 44, name: "Titan Esports Club", power: 64, potential: 70, region: "China" },
  { id: 45, name: "Trace Esports", power: 72, potential: 78, region: "China" },
  { id: 46, name: "Tyloo", power: 66, potential: 72, region: "China" },
  { id: 47, name: "XLG Esports", power: 61, potential: 67, region: "China" },
  { id: 48, name: "Dragon Ranger Gaming", power: 60, potential: 66, region: "China" }
];

export const teamLogos = {
  "100 Thieves": "assets/team_logos/100_thieves.png",
  "Cloud9": "assets/team_logos/cloud9.png",
  "Evil Geniuses": "assets/team_logos/evil_geniuses.png",
  "FURIA": "assets/team_logos/furia.png",
  "KRÜ Esports": "assets/team_logos/kru_esports.png",
  "Leviatan": "assets/team_logos/leviatan.png",
  "Leviatán": "assets/team_logos/leviatan.png",
  "LOUD": "assets/team_logos/loud.png",
  "MIBR": "assets/team_logos/mibr.png",
  "NRG": "assets/team_logos/nrg.png",
  "Sentinels": "assets/team_logos/sentinels.png",
  "G2 Esports": "assets/team_logos/g2_esports.png",
  "2GAME Esports": "assets/team_logos/2game_esports.png",
  "Team Liquid": "assets/team_logos/team_liquid.png",
  "GiantX": "assets/team_logos/giantx.png",
  "Natus Vincere": "assets/team_logos/natus_vincere.png",
  "Fnatic": "assets/team_logos/fnatic.png",
  "BBL Esports": "assets/team_logos/bbl_esports.png",
  "Karmine Corp": "assets/team_logos/karmine_corp.png",
  "Team Heretics": "assets/team_logos/team_heretics.png",
  "Vitality": "assets/team_logos/vitality.png",
  "Apeks": "assets/team_logos/apeks.png",
  "KOI": "assets/team_logos/koi.png",
  "FUT Esports": "assets/team_logos/fut_esports.png",
  "Gentle Mates": "assets/team_logos/gentle_mates.png",
  "Zeta Divison": "assets/team_logos/zeta_division.png",
  "Team Secret": "assets/team_logos/team_secret.png",
  "Paper Rex": "assets/team_logos/paper_rex.png",
  "DetonationFocusMe": "assets/team_logos/detonation_focus_me.png",
  "Gen.G": "assets/team_logos/gen_g.png",
  "DRX": "assets/team_logos/drx.png",
  "T1": "assets/team_logos/t1.png",
  "Boom Esports": "assets/team_logos/boom_esports.png",
  "Nongshim Redforce": "assets/team_logos/nongshim_redforce.png",
  "Talon": "assets/team_logos/talon_esports.png",
  "Global Esports": "assets/team_logos/global_esports.png",
  "Rex Regum Qeon": "assets/team_logos/rex_regum_qeon.png",
  "All Gamers": "assets/team_logos/all_gamers.png",
  "Edward Gaming": "assets/team_logos/edward_gaming.png",
  "FunPlus Phoenix": "assets/team_logos/funplus_phoenix.png",
  "Wolves Esports": "assets/team_logos/wolves_esports.png",
  "Bilibili Gaming": "assets/team_logos/bilibili_gaming.png",
  "JD Gaming": "assets/team_logos/jd_gaming.png",
  "Nova Esports": "assets/team_logos/nova_esports.png",
  "Titan Esports Club": "assets/team_logos/titan_esports_club.png",
  "Trace Esports": "assets/team_logos/trace_esports.png",
  "Tyloo": "assets/team_logos/tyloo.png",
  "XLG Esports": "assets/team_logos/xlg_esports.png",
  "Dragon Ranger Gaming": "assets/team_logos/dragon_ranger_gaming.png"
};

export function getTeamByName(teamName) {
  return teams.find(team => team.name === teamName);
}
